version: "3.3"
services:
  web:
    image: wodby/php-nginx
    ports:
      - "9002:80"
    restart: always
    environment:
      - NGINX_SERVER_NAME=zblog
    volumes:
      - ./app/:/var/www/html/
      - ./templates:/etc/gotpl
